#networks:
#  mail-network:
#    driver: bridge

services:

  db:
    container_name: db
    image: postgres:15
    environment:
      - POSTGRES_DB=mailbase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 28282:5432
    restart: unless-stopped
#    networks:
#      - mail-network

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_SKIP_TESTS=true
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/mailbase
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    restart: unless-stopped
    depends_on:
      - db
#    networks:
#      - mail-network