apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-app-deployment
  labels:
    app: mail-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mail-app
  template:
    metadata:
      labels:
        app: mail-app
    spec:
      containers:
        - name: mail-app
          image: andrey1510/mail-app:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: mail-app-service
spec:
  selector:
    app: mail-app
  ports:
    - protocol: TCP
      port: 8484
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db-deployment
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db-container
        image: postgres:15
        ports:
        - containerPort: 28282
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password  
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-database               
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 28082
      targetPort: 28282
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgres-url: "postgres-service"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: user
  postgres-password: password
  postgres-database: mailbase
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mail-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: mail-app.com
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: mail-app-service
                port:
                  number: 8888