spring:
  datasource:
    url: jdbc:h2:mem:postalbase
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true     #http://localhost:8080/h2-console

springdoc:
  paths-to-match: /api/**
  swagger-ui:
    enabled: true
    filter: true