server:
  port: 8080

spring:
  application:
    name: mail-app
  datasource:
    url: jdbc:postgresql://localhost:28282/mailbase
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  paths-to-match: /api/**
  swagger-ui:
    enabled: true
    filter: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'